version: '3.8'

services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.0.93
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=esp_tracker
    restart: unless-stopped
    networks:
      - tracker-network

networks:
  tracker-network:
    driver: bridge 